# Generated by Django 4.0.6 on 2022-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Blog Post', max_length=255),
        ),
    ]
