# Generated by Django 4.0.6 on 2022-08-02 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersblog', '0006_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='coding', max_length=255),
        ),
    ]
