# Generated by Django 4.0.6 on 2022-08-05 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersblog', '0009_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link above to read blog post.', max_length=255),
        ),
    ]
