# Generated by Django 4.0.6 on 2022-08-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playersblog', '0013_profile_amazon_url_profile_fb_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='etsy_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
